// authentication and account
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS'
export const AUTH_SIGNUP_SUCCESS = 'AUTH_SIGNUP_SUCCESS'
export const AUTH_VERIFY_MAIL_SUCCESS = 'AUTH_VERIFY_MAIL_SUCCESS'
export const AUTH_FORGOT_PASS_SUCCESS = 'AUTH_FORGOT_PASS_SUCCESS'
export const AUTH_RESET_PASS_SUCCESS = 'AUTH_RESET_PASS_SUCCESS'
export const AUTH_REFRESH_TOKEN_SUCCESS = 'AUTH_REFRESH_TOKEN_SUCCESS'
export const AUTH_LOGOUT_SUCCESS = 'AUTH_LOGOUT_SUCCESS'

export const USER_GET_PROFILE_SUCCESS = 'USER_GET_PROFILE_SUCCESS'
export const USER_GET_PUBLIC_PROFILE_SUCCESS = 'USER_GET_PUBLIC_PROFILE_SUCCESS'
export const USER_GET_SETTING_SUCCESS = 'USER_GET_SETTING_SUCCESS'

// blog
export const BLOG_GET_TAGS_SUCCESS = 'BLOG_GET_TAGS_SUCCESS'
export const BLOG_GET_COUNT_SUCCESS = 'BLOG_GET_COUNT_SUCCESS'
export const BLOG_GET_LIST_SUCCESS = 'BLOG_GET_LIST_SUCCESS'
export const BLOG_GET_DETAIL_SUCCESS = 'BLOG_GET_DETAIL_SUCCESS'

export const BLOG_SET_SEARCH_KEY = 'BLOG_SET_SEARCH_KEY'
export const BLOG_SET_SEARCH_STR = 'BLOG_SET_SEARCH_STR'
export const BLOG_SET_PAGE_INFO = 'BLOG_SET_PAGE_INFO'
export const BLOG_SET_SORT_ORDER = 'BLOG_SET_SORT_ORDER'
